# -*- coding: utf-8 -*-
"""Solucion_caso_practico_IEP_IAA_CV_u1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQx5tJCiGQCLfVjj_Ms3kuz6veuf5lv6

# Caso Práctico Unidad 1 – Tratamiento de Imágenes con Python y OpenCV

## Preguntas críticas para el desarrollo del ejercicio

1. **¿Cómo verificamos si la imagen fue cargada correctamente en OpenCV?**  
   Para evitar errores si la ruta del archivo está mal o el archivo no es válido.

2. **¿Cuál es la diferencia visual y estructural entre la imagen original y su versión en escala de grises?**  
   Para entender cómo cambia la representación de la información visual.

3. **¿Qué tipo de filtro de desenfoque es más adecuado para reducir el ruido sin perder detalles importantes?**  
   Para seleccionar el mejor filtro entre opciones como `GaussianBlur`, `medianBlur` o `bilateralFilter`.

4. **¿Qué parámetros del algoritmo Canny afectan la sensibilidad en la detección de bordes y cómo elegirlos?**  
   Para afinar los resultados del algoritmo ajustando `threshold1` y `threshold2`.

5. **¿Cómo garantizamos que las imágenes procesadas se guarden correctamente en el entorno de Google Colab o Drive?**  
   Para verificar que la persistencia de datos funcione y no haya pérdidas.

6. **¿Qué utilidad tiene esta cadena de procesamiento (grises → desenfoque → bordes) antes de aplicar modelos de IA?**  
   Para reflexionar sobre el valor del preprocesamiento en sistemas de visión por computadora.

---

## Resultados esperados del caso práctico

| Etapa                            | Resultado Esperado                                                              |
|----------------------------------|----------------------------------------------------------------------------------|
| 1. Lectura y visualización       | Imagen cargada correctamente y visualizada en color                             |
| 2. Conversión a escala de grises | Imagen en blanco y negro con contornos bien definidos                           |
| 3. Filtro de desenfoque          | Imagen suavizada con reducción notable del ruido                                |
| 4. Detección de bordes (Canny)   | Imagen con contornos marcados en blanco sobre fondo negro                       |
| 5. Guardado de resultados        | Tres imágenes guardadas: escala de grises, desenfocada y bordes (`.png` o `.jpg`)|
| 6. Código comentado              | Código limpio y con comentarios que expliquen cada parte del flujo              |
| 7. Manejo de errores             | Uso de `try-except` para evitar fallos silenciosos al leer o guardar imágenes   |
"""

# Procedemos con la instalación de librerias
!pip install opencv-python-headless --quiet

import cv2
import numpy as np
import matplotlib.pyplot as plt
import urllib.request
import os

# Decidí elegir una imagen de dominio público
image_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PNG_transparency_demonstration_1.png/640px-PNG_transparency_demonstration_1.png'
image_path = 'original_image.png'

# Descargar la imagen si no existe
try:
    if not os.path.exists(image_path):
        urllib.request.urlretrieve(image_url, image_path)
        print("Imagen descargada correctamente.")
    else:
        print("ℹImagen ya estaba descargada.")
except Exception as e:
    print(f"Error al descargar la imagen: {e}")

# 📷 Leer la imagen con OpenCV
image = cv2.imread(image_path)

# Validación
if image is None:
    raise ValueError("No se pudo cargar la imagen.")
else:
    print("Imagen cargada correctamente.")

# Convertir de BGR (OpenCV) a RGB para visualización con matplotlib
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Mostrar imagen original
plt.imshow(image_rgb)
plt.title("Imagen Original")
plt.axis('off')
plt.show()

# Convertimos a escala de grises
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Mostramos imagen en escala de grises
plt.imshow(gray_image, cmap='gray')
plt.title("Imagen en Escala de Grises")
plt.axis('off')
plt.show()

# Guardamos
cv2.imwrite("imagen_gris.png", gray_image)

# Aplicamos desenfoque gaussiano
blurred_image = cv2.GaussianBlur(gray_image, (5, 5), 0)

# Mostramos imagen desenfocada
plt.imshow(blurred_image, cmap='gray')
plt.title("Imagen Desenfocada (Gaussian Blur)")
plt.axis('off')
plt.show()

# Guardamos
cv2.imwrite("imagen_desenfocada.png", blurred_image)

# Aplicamos entonces detección de bordes con Canny
edges = cv2.Canny(blurred_image, threshold1=50, threshold2=150)

# Mostramos bordes detectados
plt.imshow(edges, cmap='gray')
plt.title("Detección de Bordes (Canny)")
plt.axis('off')
plt.show()

# Guardamos
cv2.imwrite("imagen_bordes.png", edges)

import os

print("Archivos guardados:")
for file in ["imagen_gris.png", "imagen_desenfocada.png", "imagen_bordes.png"]:
    print(f" {file} - {'Existe' if os.path.exists(file) else 'No encontrado'}")

"""## Conclusión del Caso Práctico: Tratamiento de Imágenes con Python y OpenCV

En este ejercicio se abordaron de forma práctica los conceptos fundamentales del tratamiento de imágenes en el contexto de la Visión por Computador. Se cumplió de manera satisfactoria el enunciado propuesto al completar cada una de las etapas solicitadas:

1. **Lectura y visualización de imagen**  
   Se utilizó una imagen en formato PNG desde una fuente pública (Wikimedia Commons) y fue leída correctamente con OpenCV. Se visualizó en su forma original aplicando la conversión de espacio de color BGR a RGB para compatibilidad con Matplotlib.

2. **Conversión a escala de grises**  
   Se convirtió la imagen a escala de grises, permitiendo reducir la dimensionalidad de los datos y prepararla para posteriores etapas de procesamiento.

3. **Aplicación de filtro de desenfoque**  
   Se aplicó un filtro Gaussiano para reducir el ruido presente en la imagen, lo cual es una práctica común y necesaria antes de realizar operaciones de detección de bordes.

4. **Detección de bordes (Canny)**  
   Se utilizó el algoritmo de detección de bordes de Canny, un método clásico y eficaz en visión por computadora. Esta técnica permitió resaltar los contornos y transiciones abruptas en la imagen, facilitando la segmentación y análisis estructural.

5. **Guardado de imágenes procesadas**  
   Cada una de las etapas generó una imagen de salida (en escala de grises, desenfocada y con bordes detectados), las cuales fueron guardadas correctamente en el entorno local del notebook.

### Valor añadido
Además de cumplir los requerimientos, se integró manejo de errores básico, comentarios explicativos para cada bloque de código, y visualización clara con `matplotlib`. Esto refuerza la comprensión de cada paso y facilita la reutilización del código en otros casos.

---

### Conclusión Final:
Este caso práctico permitió aplicar herramientas reales del entorno de Computer Vision en un flujo básico pero esencial. Sentó las bases para tareas más avanzadas como segmentación, detección de objetos, clasificación de imágenes, o implementación de modelos con redes neuronales convolucionales (CNN).


"""